version: "3.8"

services:
    db:
        image: postgres:16.2-alpine
        container_name: db
        restart: always
        volumes:
            - ./datasourse:/docker-entrypoint-initdb.d
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: introducingtutor
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5400:5432"
volumes:
    postgres_data:
